# Generated by Django 5.0.3 on 2024-03-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=64)),
                ('descripion', models.CharField(max_length=200)),
                ('balance', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
