# Generated by Django 5.0.3 on 2024-03-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_descripion_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='institution',
            field=models.CharField(choices=[('DES', 'Desjardins'), ('RBC', 'Royal Bank of Canada'), ('BNC', 'Banque Nationale'), ('VIE', 'Canada Vie'), ('SUN', 'Sun Life')], default='DES', max_length=3),
        ),
    ]
