# Generated by Django 3.2.6 on 2024-03-23 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DES', 'Desjardins'), ('RBC', 'Royal Bank of Canada'), ('BNC', 'Banque Nationale'), ('VIE', 'Canada Vie'), ('SUN', 'Sun Life')], default='DES', max_length=3)),
                ('description', models.CharField(max_length=400)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desjardins',
            fields=[
                ('institution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.institution')),
                ('security_questions_1', models.TextField()),
                ('security_answer_1', models.CharField(max_length=50)),
                ('security_questions_2', models.TextField()),
                ('security_answer_2', models.CharField(max_length=50)),
                ('security_questions_3', models.TextField()),
                ('security_answer_3', models.CharField(max_length=50)),
            ],
            bases=('accounts.institution',),
        ),
        migrations.AlterField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.institution'),
        ),
    ]
