# Generated by Django 3.2.6 on 2024-03-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20240323_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='institution',
            field=models.CharField(choices=[('DES', 'Desjardins'), ('RBC', 'Royal Bank of Canada'), ('BNC', 'Banque Nationale'), ('VIE', 'Canada Vie'), ('SUN', 'Sun Life')], default='DES', max_length=3),
        ),
    ]
