# Generated by Django 3.2.6 on 2024-03-24 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_account_parent_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='auth.user'),
            preserve_default=False,
        ),
    ]
