# Generated by Django 3.2.6 on 2024-03-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_institution_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='institution',
        ),
    ]
