# Generated by Django 3.2.6 on 2024-03-27 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_account_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='accounts.account')),
            ],
            options={
                'get_latest_by': 'value_date',
            },
        ),
    ]
