# Generated by Django 3.2.6 on 2024-03-27 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_accountvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvalue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_values', to='auth.user'),
            preserve_default=False,
        ),
    ]
