# Generated by Django 3.2.6 on 2024-03-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_accountvalue_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'get_latest_by': 'last_updated'},
        ),
    ]
