# Generated by Django 3.2.6 on 2024-03-28 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20240328_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvalue',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountvalue',
            name='value_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 22, 10, 50, 935544, tzinfo=utc)),
        ),
    ]
