# Generated by Django 3.2.6 on 2024-04-03 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_assets', '0002_auto_20240402_2142'),
        ('accounts', '0016_auto_20240328_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='asset_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_assets.asset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='accounts.institution'),
        ),
        migrations.DeleteModel(
            name='AccountValue',
        ),
    ]
