# Generated by Django 3.2.6 on 2024-04-04 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20240402_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.institution'),
        ),
    ]
