# Generated by Django 3.2.6 on 2024-03-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_accountvalue_value_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvalue',
            name='value_float',
            field=models.FloatField(default=10),
        ),
    ]
