# Generated by Django 3.2.6 on 2024-03-25 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RES', 'Real Estate'), ('VEH', 'Vehicle'), ('STK', 'Stocks'), ('LUX', 'Luxury Item'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('description', models.CharField(max_length=400)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
