# Generated by Django 3.2.6 on 2024-04-01 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilities.utilities


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('networth', '0002_alter_manualasset_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAssetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_date', models.DateField(default=utilities.utilities.return_date_time)),
                ('value_float', models.FloatField(default=10)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('manual_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='networth.manualasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'value_date',
            },
        ),
    ]
