# Generated by Django 3.2.6 on 2024-04-07 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('networth', '0004_auto_20240402_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualasset',
            name='user_child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manual_assets', to='auth.user'),
            preserve_default=False,
        ),
    ]
