# Generated by Django 3.2.6 on 2024-04-03 01:42

import apps.core_assets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='balance',
            new_name='current_value',
        ),
        migrations.AddField(
            model_name='asset',
            name='child_class',
            field=models.CharField(default='Asset', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AssetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_date', models.DateField(default=apps.core_assets.models.return_date_time)),
                ('value_float', models.FloatField(default=10)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_values', to='core_assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'value_date',
            },
        ),
    ]
