# Generated by Django 3.2.6 on 2024-04-04 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_assets', '0005_alter_asset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='child_class',
            field=models.CharField(default='%(app_label)s_%(class)ss', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_assets_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
