# Generated by Django 3.2.6 on 2024-04-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_assets', '0011_alter_asset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='child_class',
            field=models.CharField(default='Asset', max_length=100),
        ),
    ]
